dsh_newform_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DshNewformBundle:Default:index }

dsh_realworldform:
     pattern: /
     defaults: { _controller: DshNewformBundle:Realworldform:Realform }
