dsh_newform_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DshNewformBundle:Default:index }

dsh_realworldform:
     pattern: /goodbye/{banana}
     defaults: { _controller: DshNewformBundle:Realworldform:Realform }
