parameters:
#    dsh_newform.example.class: Dsh\NewformBundle\Example

services:
#    dsh_newform.example:
#        class: %dsh_newform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]






# src/Acme/HelloBundle/Resources/config/services.yml
parameters:
    # ...
    Dsh.Formcontroller.Newform.class: Dsh\NewformBundle\Controller\formController

services:
    Dsh.FormController.controller:
        class: "%Dsh.formcontroller.Newform.class%"