parameters:
#    newform.example.class: Dsh\NewformBundle\Example

services:
#    newform.example:
#        class: %newform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
