parameters:
#    dsh_task.example.class: Dsh\TaskBundle\Example

services:
#    dsh_task.example:
#        class: %dsh_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
